remove textarea and add cards
midudev/midu-timeszones-latam pull request #11
Opened 2022-09-09 20:52 UTC by francescoalterio

2022-09-09 20:53 UTC, francescoalterio commented
Se elimino el textarea y se agrego un sistema de cartas

2022-09-09 20:54 UTC, francescoalterio commented
![midu-times](https://user-images.githubusercontent.com/83098596/189443244-25b425e5-2e2b-4f99-85eb-ce4419f17e37.png)

2022-09-14 17:36 UTC, paabloLC commented on index.html
> +      <section></section>
este section vacío, está aquí por algo en concreto? =)

2022-09-14 17:38 UTC, paabloLC commented on main.js
> +  $section.innerHTML = html.join('')
vale, ahora veo para qué está ahí el section, yo lo implementaría de otra forma. El section podría englobar todas las cards, suponiendo que la estructura de la página esté montada con sections. (no lo he mirado) en cuyo caso, cada card la pondría en un div y dentro ya su correspondiente semántica. Span, label, lo que necesites.

Saludos! =)

2022-09-14 17:39 UTC, paabloLC requested changes
I hope it helps =))

2022-09-14 19:00 UTC, francescoalterio commented on main.js
> +  $section.innerHTML = html.join('')
Hola, cada card tiene es un <article>, y dentro de la card hay un <span>(la hora) y un <p>(las banderas). El usar <article> fue por los estilos de picoCSS utilizados en el proyecto. Despues de generar cada article por cada hora se insertan directamente en dicho section.

Saludos amigo! :)

2022-09-14 19:04 UTC, francescoalterio commented on main.js
> +  $section.innerHTML = html.join('')
Mi semántica no es la mejor jajajajajaja, si puede ser mejorada excelente! =)

2023-08-14 17:31 UTC, closed without merging